[project]
name = "lenses-mcp"
version = "0.2.0"
description = "Lenses.io"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp==2.12.0",
    "loguru>=0.7.3",
    "typing-extensions>=4.15.0",
    "websockets>=15.0.1",
]
