#!/usr/bin/env bash
echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
# Source commit not yet (?) supported by docker hub.
echo "SOURCE_COMMIT: ${SOURCE_COMMIT}"
export BUILD_COMMIT="$(git rev-parse HEAD)"
echo "BUILD_COMMIT: ${BUILD_COMMIT}"
export BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "BUILD_TIME: ${BUILD_TIME}"
echo "DOCKER_REPO: ${DOCKER_REPO}"

VERSION=$(grep ^version pyproject.toml | sed -re 's/.*"(.*)".*/\1/')
MINOR_VERSION=$(echo $VERSION | sed -re 's/([0-9]+\.[0-9]+)\..*/\1/')

# Build and push the images
docker buildx create \
       --name mybuilder \
       --driver docker-container \
       --bootstrap \
       --use

docker buildx build \
       --platform=linux/amd64,linux/arm64 \
       --push \
       --build-arg "BUILD_BRANCH=${SOURCE_BRANCH}" \
       --build-arg "BUILD_COMMIT=${BUILD_COMMIT}" \
       --build-arg "BUILD_TIME=${BUILD_TIME}" \
       --build-arg "DOCKER_REPO=${DOCKER_REPO}" \
       --tag lensesio/mcp:${VERSION} \
       --tag lensesio/mcp:${MINOR_VERSION} \
       --tag lensesio/mcp:latest \
       .
