"""
Pydantic models for MCP tool inputs and outputs.

This module exports:
- Base model classes (BaseInputModel, BaseOutputModel)
- Mixin classes (EnvironmentMixin)
- Annotated type aliases for reusable field definitions
- All domain-specific input/output models
"""
from models.base import (
    BaseInputModel,
    BaseOutputModel,
    ClusterName,
    ConnectionName,
    ConnectorName,
    ConsumerGroupId,
    DatasetName,
    DictOutput,
    EntityName,
    EnvironmentMixin,
    EnvironmentName,
    K8sNamespace,
    K8sPodName,
    ListOutput,
    MetricsListOutput,
    OffsetNumber,
    PartitionCount,
    PartitionNumber,
    ReplicationFactor,
    ResourceName,
    SingleItemOutput,
    SqlProcessorId,
    StringOutput,
    TopicConfigs,
    TopicName,
)
from models.environments import (
    CheckEnvironmentHealthInput,
    CheckEnvironmentHealthOutput,
    CreateEnvironmentInput,
    CreateEnvironmentOutput,
    EnvironmentHealthSummary,
    GetEnvironmentInput,
    GetEnvironmentOutput,
    ListEnvironmentsOutput,
)
from models.sql import ExecuteSQLInput, ExecuteSQLOutput
from models.sql_processors import (
    CreateSqlProcessorInput,
    CreateSqlProcessorOutput,
    DeleteSqlProcessorInput,
    DeleteSqlProcessorOutput,
    GetDeploymentTargetsInput,
    GetDeploymentTargetsOutput,
    GetPodLogsInput,
    GetPodLogsOutput,
    GetSqlProcessorInput,
    GetSqlProcessorOutput,
    ListSqlProcessorsInput,
    ListSqlProcessorsOutput,
)
from models.kafka_connectors import (
    CreateKafkaConnectorInput,
    CreateKafkaConnectorOutput,
    DeleteKafkaConnectorInput,
    DeleteKafkaConnectorOutput,
    GetKafkaConnectorTargetDefinitionInput,
    GetKafkaConnectorTargetDefinitionOutput,
    ListKafkaConnectorsInput,
    ListKafkaConnectorsOutput,
    RestartKafkaConnectorTaskInput,
    RestartKafkaConnectorTaskOutput,
    SetActionOnKafkaConnectorInput,
    SetActionOnKafkaConnectorOutput,
    ValidateConnectorConfigurationInput,
    ValidateConnectorConfigurationOutput,
)
from models.kafka_consumer_groups import (
    ConsumerGroupOffsetItem,
    DeleteConsumerGroupInput,
    DeleteConsumerGroupOffsetsInput,
    DeleteConsumerGroupOffsetsOutput,
    DeleteConsumerGroupOutput,
    DeleteConsumerGroupTopicPartitionOffsetInput,
    DeleteConsumerGroupTopicPartitionOffsetOutput,
    ListConsumerGroupsByTopicInput,
    ListConsumerGroupsByTopicOutput,
    ListConsumerGroupsInput,
    ListConsumerGroupsOutput,
    TopicPartitionItem,
    UpdateConsumerGroupOffsetsInput,
    UpdateConsumerGroupOffsetsOutput,
    UpdateConsumerGroupTopicPartitionOffsetInput,
    UpdateConsumerGroupTopicPartitionOffsetOutput,
)
from models.topics import (
    AddTopicPartitionsInput,
    AddTopicPartitionsOutput,
    CreateTopicInput,
    CreateTopicOutput,
    CreateTopicWithSchemaInput,
    CreateTopicWithSchemaOutput,
    GetDatasetInput,
    GetDatasetMessageMetricsInput,
    GetDatasetMessageMetricsOutput,
    GetDatasetOutput,
    GetTopicBrokerConfigsInput,
    GetTopicBrokerConfigsOutput,
    GetTopicInput,
    GetTopicMetadataInput,
    GetTopicMetadataOutput,
    GetTopicOutput,
    GetTopicPartitionsInput,
    GetTopicPartitionsOutput,
    ListDatasetsInput,
    ListDatasetsOutput,
    ListTopicMetadataInput,
    ListTopicMetadataOutput,
    ListTopicsInput,
    ListTopicsOutput,
    ResendMessageInput,
    ResendMessageOutput,
    TopicConfigItem,
    UpdateDatasetTopicDescriptionInput,
    UpdateDatasetTopicDescriptionOutput,
    UpdateDatasetTopicTagsInput,
    UpdateDatasetTopicTagsOutput,
    UpdateTopicConfigInput,
    UpdateTopicConfigOutput,
    UpdateTopicMetadataInput,
    UpdateTopicMetadataOutput,
)

__all__ = [
    # Base models and mixins
    "BaseInputModel",
    "BaseOutputModel",
    "EnvironmentMixin",
    # Generic output models
    "DictOutput",
    "ListOutput",
    "MetricsListOutput",
    "SingleItemOutput",
    "StringOutput",
    # Annotated type aliases for reusable fields
    "ClusterName",
    "ConnectionName",
    "ConnectorName",
    "ConsumerGroupId",
    "DatasetName",
    "EntityName",
    "EnvironmentName",
    "K8sNamespace",
    "K8sPodName",
    "OffsetNumber",
    "PartitionCount",
    "PartitionNumber",
    "ReplicationFactor",
    "ResourceName",
    "SqlProcessorId",
    "TopicConfigs",
    "TopicName",
    # SQL models
    "ExecuteSQLInput",
    "ExecuteSQLOutput",
    # SQL Processor models
    "ListSqlProcessorsInput",
    "ListSqlProcessorsOutput",
    "GetSqlProcessorInput",
    "GetSqlProcessorOutput",
    "CreateSqlProcessorInput",
    "CreateSqlProcessorOutput",
    "DeleteSqlProcessorInput",
    "DeleteSqlProcessorOutput",
    "GetDeploymentTargetsInput",
    "GetDeploymentTargetsOutput",
    "GetPodLogsInput",
    "GetPodLogsOutput",
    # Kafka Connector models
    "ListKafkaConnectorsInput",
    "ListKafkaConnectorsOutput",
    "GetKafkaConnectorTargetDefinitionInput",
    "GetKafkaConnectorTargetDefinitionOutput",
    "CreateKafkaConnectorInput",
    "CreateKafkaConnectorOutput",
    "SetActionOnKafkaConnectorInput",
    "SetActionOnKafkaConnectorOutput",
    "RestartKafkaConnectorTaskInput",
    "RestartKafkaConnectorTaskOutput",
    "DeleteKafkaConnectorInput",
    "DeleteKafkaConnectorOutput",
    "ValidateConnectorConfigurationInput",
    "ValidateConnectorConfigurationOutput",
    # Kafka Consumer Group models
    "ListConsumerGroupsInput",
    "ListConsumerGroupsOutput",
    "ListConsumerGroupsByTopicInput",
    "ListConsumerGroupsByTopicOutput",
    "UpdateConsumerGroupOffsetsInput",
    "UpdateConsumerGroupOffsetsOutput",
    "DeleteConsumerGroupOffsetsInput",
    "DeleteConsumerGroupOffsetsOutput",
    "UpdateConsumerGroupTopicPartitionOffsetInput",
    "UpdateConsumerGroupTopicPartitionOffsetOutput",
    "DeleteConsumerGroupTopicPartitionOffsetInput",
    "DeleteConsumerGroupTopicPartitionOffsetOutput",
    "DeleteConsumerGroupInput",
    "DeleteConsumerGroupOutput",
    "ConsumerGroupOffsetItem",
    "TopicPartitionItem",
    # Environment models
    "GetEnvironmentInput",
    "GetEnvironmentOutput",
    "CreateEnvironmentInput",
    "CreateEnvironmentOutput",
    "CheckEnvironmentHealthInput",
    "CheckEnvironmentHealthOutput",
    "EnvironmentHealthSummary",
    "ListEnvironmentsOutput",
    "ListTopicsInput",
    "ListTopicsOutput",
    "GetTopicInput",
    "GetTopicOutput",
    "GetTopicPartitionsInput",
    "GetTopicPartitionsOutput",
    "CreateTopicInput",
    "CreateTopicOutput",
    "CreateTopicWithSchemaInput",
    "CreateTopicWithSchemaOutput",
    "UpdateTopicConfigInput",
    "UpdateTopicConfigOutput",
    "TopicConfigItem",
    "GetTopicBrokerConfigsInput",
    "GetTopicBrokerConfigsOutput",
    "AddTopicPartitionsInput",
    "AddTopicPartitionsOutput",
    "ResendMessageInput",
    "ResendMessageOutput",
    "ListTopicMetadataInput",
    "ListTopicMetadataOutput",
    "GetTopicMetadataInput",
    "GetTopicMetadataOutput",
    "UpdateTopicMetadataInput",
    "UpdateTopicMetadataOutput",
    "ListDatasetsInput",
    "ListDatasetsOutput",
    "GetDatasetInput",
    "GetDatasetOutput",
    "GetDatasetMessageMetricsInput",
    "GetDatasetMessageMetricsOutput",
    "UpdateDatasetTopicDescriptionInput",
    "UpdateDatasetTopicDescriptionOutput",
    "UpdateDatasetTopicTagsInput",
    "UpdateDatasetTopicTagsOutput",
]

